/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: df946d86bbb5aa54c6cd45e70651bcd8)
interface __BaseEnv_Env {
	DB: D1Database;
	AI: Ai;
	TriageAgent: DurableObjectNamespace<import("./src/server").TriageAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "TriageAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
